### ISSUE TITLE
Meaning of each time reported by mutpy

### ISSUE THREAD

**Issue by jose** [mutpy/mutpy#70]
Hi,

Here's an dummy example of a YAML report generated by mutpy:

```yaml
coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 90.0
mutations:
- exception_traceback: "Traceback (most recent call last): ..."
  killer: my_test
  module: my_module
  mutations:
  - lineno: 98
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 8.54907512664795

...

number_of_tests: 3
targets:
- my_module
tests:
- name: my_test
  target: null
  time: 28.27469778060913
time_stats:
  create_mutant_module: 0.1439199447631836
  create_target_ast: 0.03343963623046875
  mutate_module: 225.59084630012512
  run_tests_with_mutant: 210.12824749946594
total_time: 257.5487313270569
```

as we can see in this example, time is reported 7 times and it isn't clear (at least to me) what's the meaning of some time values.

1. `time: 8.54907512664795`, time to kill the mutant.
2. `time: 28.27469778060913`, time to run all tests before mutation analysis takes place **???**.
3. `create_mutant_module: 0.1439199447631836`, **what does 'create mutant module' mean or imply?**
4. `create_target_ast: 0.03343963623046875`, **what does 'create target ast' mean or imply?**
5. `mutate_module: 225.59084630012512`, **what does 'mutate module' mean or imply?**
6. `run_tests_with_mutant: 210.12824749946594`, **which mutant?**
7. `total_time: 257.5487313270569`, I believe this is the sum of some other time values, but which ones **???**.

Any intel on these time values would be appreciated.

--
Best,
Jose
